version: '3.3'
services:
  nginx:
    build:
      args:
        nginx_port: 80
        nginx_version: ${NGINX_VERSION}
        nginx_vhost_name: ${NGINX_VHOST_NAME}
      context: ./docker/nginx
    container_name: ${NGINX_CONTAINER_NAME}
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      - ./config/nginx/app.conf.tpl:/etc/nginx/conf.d/app.conf.tpl:cached
      - ${HOST_PROJECT_ROOT}:${CONTAINER_PROJECT_ROOT}:cached
    ports:
      - "${NGINX_PORT}:80"
    networks:
      testtask:
        ipv4_address: ${NGINX_IP}
    depends_on:
      - php-fpm

  php-fpm:
    build:
      args:
        php_version: ${PHP_VERSION}
      context: ./docker/php-fpm
    env_file:
      - .env
    container_name: ${PHP_FPM_CONTAINER_NAME}
    depends_on:
      - mysql
    volumes:
      - ${HOST_PROJECT_ROOT}:${CONTAINER_PROJECT_ROOT}:cached
      - ./config/php/php.ini:/usr/local/etc/php/php.ini:cached
    networks:
      - ${NETWORK_NAME}

  mysql:
    container_name: ${MYSQL_CONTAINER_NAME}
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    image: percona:${MYSQL_VERSION}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-log:/var/log/mysql
      - mysql-lib:/var/lib/mysql
      - ${HOST_PROJECT_ROOT}:${CONTAINER_PROJECT_ROOT}:cached
      - ./config/mysql/config.cnf:/etc/my.cnf.d/config.cnf
    networks:
      - ${NETWORK_NAME}
volumes:
  mysql-log:
  mysql-lib:

networks:
  testtask:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}
